import type { HotMarket } from "./types";

export const sampleHotMarkets: HotMarket[] = [
  {
    id: "polymarket:sample-btc",
    platform: "polymarket",
    externalId: "sample-btc",
    title: "Will Bitcoin hit a new all-time high this month?",
    category: "crypto",
    url: "https://polymarket.com",
    status: "sample",
    closeTime: new Date(Date.now() + 12 * 86_400_000).toISOString(),
    snapshot: {
      marketId: "polymarket:sample-btc",
      ts: new Date().toISOString(),
      price: 0.57,
      volume: 925000,
      volume24h: 184000,
      liquidity: 410000,
      spread: 0.02,
      openInterest: null,
      bestBid: 0.56,
      bestAsk: 0.58,
    },
    trend: {
      marketId: "polymarket:sample-btc",
      score: 82,
      volumeScore: 84,
      priceScore: 74,
      liquidityScore: 80,
      openInterestScore: 0,
      contextScore: 62,
      recencyScore: 12,
      why: ["Elevated trading volume", "Fast probability move", "Related news or Reddit mentions found"],
      computedAt: new Date().toISOString(),
    },
    contextItems: [
      {
        id: "sample-context",
        marketId: "polymarket:sample-btc",
        source: "rss",
        title: "Crypto markets rally as traders watch ETF inflows",
        url: "https://www.coindesk.com",
        publishedAt: new Date().toISOString(),
        matchedKeywords: ["crypto", "markets"],
        relevanceScore: 0.5,
      },
    ],
  },
  {
    id: "kalshi:sample-fed",
    platform: "kalshi",
    externalId: "sample-fed",
    ticker: "SAMPLE-FED",
    title: "Will the Fed cut interest rates at the next meeting?",
    category: "economics",
    url: "https://kalshi.com",
    status: "sample",
    closeTime: new Date(Date.now() + 20 * 86_400_000).toISOString(),
    snapshot: {
      marketId: "kalshi:sample-fed",
      ts: new Date().toISOString(),
      price: 0.43,
      volume: 324000,
      volume24h: 76000,
      liquidity: 120000,
      spread: 0.03,
      openInterest: 220000,
      bestBid: 0.42,
      bestAsk: 0.45,
    },
    trend: {
      marketId: "kalshi:sample-fed",
      score: 74,
      volumeScore: 71,
      priceScore: 62,
      liquidityScore: 64,
      openInterestScore: 72,
      contextScore: 38,
      recencyScore: 12,
      why: ["Elevated trading volume", "Meaningful open interest"],
      computedAt: new Date().toISOString(),
    },
    contextItems: [],
  },
];
